### ISSUE TITLE
multiple chargers in different locations lead to various issues

### ISSUE THREAD

**Issue by dbarrosop** [custom-components/zaptec#61] opened 2023-11-17 10:14 UTC
Hello,
let me start by saying the result of the big refactor work feels amazing, awesome job there. I am having a minor issue though and I suspect this is due to having multiple chargers in different locations.

The first issue is that one of the chargers has a max. current of 16 and the other one of 25 and my "available currrent" is limited to 16. I suspect the component chose the minimum of the two.

The other problem is that according to the docs:

> ℹ️ NOTE! The "Available current" is the official way to control the charge current. However, it will affect all chargers connected to the installation.

But as mentioned, before, they are in different locations so this doesn't really apply here. I could be charging in both locations at the same time both at max. current.

What do you think about this problem? I suspect this isn't going to be a very rare problem, having a charger home and another one at the summer/winter cabin is probably quite common.

Thanks again for the amazing work.

Regards.

**Comment by sveinse** [comment] 2023-11-18 15:35
> The first issue is that one of the chargers has a max. current of 16 and the other one of 25 and my "available currrent" is limited to 16. I suspect the component chose the minimum of the two.

The "available current" max value is read from the attribute "max current" in the installation object. So is then the data from Zaptec portal inconsistent?

> But as mentioned, before, they are in different locations so this doesn't really apply here. I could be charging in both locations at the same time both at max. current.

I'm really curious to how this has been organized in Zaptec portal. Zaptec divides every charger into "Installation" and "Circuits" and I'm curious how this is in this case. Under each of the zaptec devices there is a "Download diagnostics". Any chance you might upload it here?

**Comment by dbarrosop** [comment] 2023-11-19 07:48
> The "available current" max value is read from the attribute "max current" in the installation object. So is then the data from Zaptec portal inconsistent?

Not sure about the installation (how can I check it?) but at least the circuit show the correct values:

<img width="316" alt="Screenshot 2023-11-19 at 08 37 53" src="https://github.com/custom-components/zaptec/assets/6246622/b0309eca-313c-4c26-a4f6-0727b04bbd10">
<img width="312" alt="Screenshot 2023-11-19 at 08 38 10" src="https://github.com/custom-components/zaptec/assets/6246622/eb74f2d7-6f15-4887-b33d-18774ddf56fb">
<img width="297" alt="Screenshot 2023-11-19 at 08 42 41" src="https://github.com/custom-components/zaptec/assets/6246622/aaeabd68-efad-4448-b5c9-017ae450aed1">
<img width="328" alt="Screenshot 2023-11-19 at 08 42 09" src="https://github.com/custom-components/zaptec/assets/6246622/bba28d05-9833-4209-a6e0-44cda3416602">


Don't you think the cause might be this?

> ℹ️ NOTE! The "Available current" is the official way to control the charge current. However, it will affect all chargers connected to the installation.

it might make sense to pick the minimum of the two if this "available current" is a global one.

> Under each of the zaptec devices there is a "Download diagnostics"

Happy to share but I am afraid I couldn't find it, where exactly is that?


Thanks for taking the time and the excellent work.

**Comment by sveinse** [comment] 2023-11-19 15:48
Good. You should have one or two installation devices as well in HA. These circuits are connected through the installation device. How does this look like for you?

**Comment by sveinse** [comment] 2023-11-19 19:08
@dbarrosop You're almost there. On the page you posted for the circuit, you can navigate to the installation device by following the circled link, see below. The download diagnostics button is available on any of the zaptec devices. They will all provide the information I was requesting.

![image](https://github.com/custom-components/zaptec/assets/13770135/0a342d92-8066-4d76-b482-93ca8b998429)

**Comment by dbarrosop** [comment] 2023-11-20 08:04
Oh, silly me was looking in zaptec's portal...

I tried downloading it but all I am getting is a file with:

```
500 Internal Server Error
Server got itself in trouble
```

Happens with both circuits.

**Comment by sveinse** [comment] 2023-11-20 19:54
Which version of zaptec do you run? Did you update to the latest (master)? The version can be read in HACS -> Integrations -> Zaptec EV Charger. The version is printed in the top left corner of the page.

**Comment by dbarrosop** [comment] 2023-11-21 07:56
I am running `v0.7.0` (latest beta version).

**Comment by dbarrosop** [comment] 2023-11-21 08:06
Ok, I changed to master and I could download the diagnostics now:

[zaptec-31b86ab6cc612b8223a37cfff753ce35-Charge circuit-a7395c2e9dd67e835f6e7e2eb31fabf7.json.txt](https://github.com/custom-components/zaptec/files/13423396/zaptec-31b86ab6cc612b8223a37cfff753ce35-Charge.circuit-a7395c2e9dd67e835f6e7e2eb31fabf7.json.txt)
[zaptec-31b86ab6cc612b8223a37cfff753ce35-Charge circuit-aa2086e87e63550d6a1c88d8d62cfbca.json.txt](https://github.com/custom-components/zaptec/files/13423398/zaptec-31b86ab6cc612b8223a37cfff753ce35-Charge.circuit-aa2086e87e63550d6a1c88d8d62cfbca.json.txt)

**Comment by sveinse** [comment] 2023-11-26 21:47
@dbarrosop I have looked into your setup. The data fetched from Zapted Portal seems to suggest that both have set their `AvailableCurrent` to 16A. I see that the chargers have `MaxCurrent` of 25A and 16A respectively. I recommend you to check the available current in the Zaptec Portal, because both seems to be limited to 16A there.

Or you can increase the value yourself in HA: You have two zaptec installation devices in your home assistant. This means you have two entities `number.<installation>_available_current`. Both is currently at 16A, but one of them should be able to be adjusted up to 25A.

I was curious if there might be a bug in the zaptec integration that wrongfully sets the available current to a lower value when loading up, but after reviewing it I can't see anything that might cause this. The entity `number.<installation>_available_current` fetches the maxium value it may be from `<installation>_max_current` which seems to be right for your setup.

If you see any unexpected changes to "Available Current" please reach out.

**Comment by dbarrosop** [comment] 2023-11-27 10:11
Where is it in the zaptec portal?

The things that are strange:

1. I can set up to 20 with no problem in the tibber (and I can confirm the change as I can see how the power consumption goes up). Actually, the tibber app shows that I can go up to 25 but I see no difference in power consumption going from 20 to 25.
2. I could also set up to 20 with no problem using this component prior to the upgrade (making service calls).

Also, I can see this in the "states":

```
number.XXXXXXXXXX_available_current 16.0

min: 0
max: 16
step: 1
mode: auto
unit_of_measurement: A
device_class: current
icon: mdi:waves
friendly_name: XXXXXX


number.XXXXXX_charger_max_current 20.0

min: 0
max: 16
step: 1
mode: auto
unit_of_measurement: A
device_class: current
icon: mdi:current-ac
friendly_name: XXXXX
```

charger_max_current is `20.0` but the max attribute is 16.0. I tried changing the states and max attributes for both numbers to 16.0 but they are reverted automatically after a few seconds.

**Comment by sveinse** [comment] 2023-11-27 10:21
- https://portal.zaptec.com/portal/dashboard
- Installations and select your installation
- Settings
- Power Management
- Scroll down and find "Charging mode". It should be set to "Manual power control" and then a box below with "Manual power control" and then the current limit for the three phases are listed.

**Comment by dbarrosop** [comment] 2023-11-27 10:40
Thanks! It was set to 11 (all three) and if I try to change it it says:

```
Value must be between 0 and 25
```

I set all three to 25 and this is what the various "numbers" say:

```
number.xxxxx_available_current state set to 25
attributes:
min: 0
max: 16
step: 1
mode: auto
unit_of_measurement: A
device_class: current
icon: mdi:waves

number.xxxxx_max_current state set to 20.0
attributes:

min: 0
max: 16
step: 1
mode: auto
unit_of_measurement: A
device_class: current
icon: mdi:current-ac
```

So looks like there is forcing the max value to 16.

**Comment by dbarrosop** [comment] 2023-11-27 20:04
> There should be two installations to chose from, one with 16A and one with 25A max current

that is the problem, that I do have 2 but both are limited to 16 in HA but are not in the zaptec portal:

```
number.xxxxx_available_current state set to 25 (set to 25 via zaptec portal)
attributes:
min: 0
max: 16
step: 1
mode: auto
unit_of_measurement: A
device_class: current
icon: mdi:waves

number.xxxxx_max_current state set to 20.0 (I set this state in the developer tools to 20.0 but didn't change anything, still capped at 16)
attributes:

min: 0
max: 16
step: 1
mode: auto
unit_of_measurement: A
device_class: current
icon: mdi:current-ac
```

and

```
number.yyyyyy_available_current state set to 16.0
attributes:
min: 0
max: 16
step: 1
mode: auto
unit_of_measurement: A
device_class: current
icon: mdi:waves

number.yyyyyy_max_current state set to 4.0
attributes:
min: 0
max: 16
step: 1
mode: auto
unit_of_measurement: A
device_class: current
icon: mdi:current-ac
```

There are also two sensors for `sensor.charge_circuit_max_current` and both show the correct max current, for instance, for the one that should support 25:

```
sensor.charge_circuit_max_current state set to 25
attributes:

unit_of_measurement: A
device_class: current
icon: mdi:current-ac
friendly_name: Charge circuit Max current
```

But still, available current for that device is capped at 16.

**Comment by sveinse** [comment] 2023-11-27 22:15
Good. I suspected that there are some issues here, and now we've confirmed that installation `xxxx` and `yyyy` exists but with wrong values on one of them. I'll start hunting in the code.

**Comment by sveinse** [comment] 2023-12-01 17:10
@dbarrosop I agree. I will publish the findings / improvements for the zaptec integration here, but we can keep the detail for your specific installation between us. Do you use facebook or linkedin? You can look me up by name and send med a DM and I'll send you my email.

**Comment by dbarrosop** [comment] 2023-12-04 08:50
Don't have facebook but sent a connection request on LinkedIn! Thx!

**Comment by sveinse** [comment] 2023-12-29 16:05
The latest release in "master" contains a promising fix to the issue you have been observing. I believe it was due to data leakage from one charger to the other that created the problems for you which is now fixed. Please test this version and report back if it fixes the problem.

**Comment by dbarrosop** [comment] 2023-12-30 11:09
I can confirm 0.7.1 fixes this issue. Awesome work :)

**Closed** 2023-12-30 11:16 UTC
Labels: bug, verification
