### ISSUE TITLE
Not possible to change configured password

### ISSUE THREAD

**Issue by markoback** [custom-components/zaptec#143] opened 2024-11-02 06:54 UTC
It is not possible to update the integration with a new zaptec portal password.

**Comment by c0mplex1** [comment] 2024-11-02 09:38
Please see:
https://github.com/custom-components/zaptec/issues/76#issue-2060075346

**Comment by sveinse** [comment] 2024-11-02 09:43
Duplicate of #76, closing issue.

**Closed by sveinse** 2024-11-02 09:43 UTC
Labels: duplicate
