### ISSUE TITLE
Error: Unable to install package azure-servicebus==7.0.1 during integration install/startup

### ISSUE THREAD

**Issue by elobilo** [custom-components/zaptec#46] opened 2023-07-24 11:05 UTC
Installed the Zaptec from the repo via HACS, no errors.
Tried to add the Zaptec integration is: Settings/Devices & Services/Integrations/+ Add Integration.
It attempts to startup the integration, and after a couple of minutes complains that there was a server error.
The logs (attached) show that azure-servicebus was not able to be installed.
My Home Assistant details are:
Home Assistant 2023.7.3
Supervisor 2023.07.1
Operating System 10.3
Frontend 20230705.1 - latest

[ZaptecIntegrationInitialisationLogtxt.txt](https://github.com/custom-components/zaptec/files/12145061/ZaptecIntegrationInitialisationLogtxt.txt)

**Comment by sveinse** [comment] 2023-07-24 13:38
It is a known error of the latest 0.5.0 release. The latest beta might work if you happen to have `azure-servicebus` installed in your HA already. It did for me. There is a pending pull request #43 that is going fix this.

This issue is a duplicate of #34.

**Comment by elobilo** [comment] 2023-07-24 15:08
Thanks, missed #34, but after reading it I install the B2 version which seems to have fixed it.

**Comment by Hellowlol** [comment] 2023-07-25 15:20
Closing, latest master will use the servicebus if it is available

**Closed by Hellowlol** 2023-07-25 15:20 UTC
