### ISSUE TITLE
Setup fails in 2023.6 - Requirements not found: ['azure-servicebus==7.0.1'].

### ISSUE THREAD

**Issue by onkelfarmor** [custom-components/zaptec#34] opened 2023-06-02 10:24 UTC
Setup fails in 2023.6 beta:

Setup failed for custom integration zaptec: Requirements for zaptec not found: ['azure-servicebus==7.0.1'].

**Comment by Hellowlol** [comment] 2023-06-02 17:39
Yeah, hopefully they will get it solved. If not i can remove this requirement. Atm this integration supports both push and pull.

**Comment by onkelfarmor** [comment] 2023-06-04 10:18
Can I do something so it works in the meantime?

**Comment by Hellowlol** [comment] 2023-06-04 10:26
You can install the latest pre release from hacs and see if it’s working

**Comment by onkelfarmor** [comment] 2023-06-04 10:30
Tried, doesn’t.

**Comment by Hellowlol** [comment] 2023-06-04 10:47
Please post the error

**Comment by onkelfarmor** [comment] 2023-06-04 10:58
I did that in the first post.

**Comment by Hellowlol** [comment] 2023-06-04 12:51
Ah, i see. I forgot to remove the requirement. I have created a new release. Please check it it works

**Comment by onkelfarmor** [comment] 2023-06-04 14:13
Now it works, thanks!

**Comment by magne74** [comment] 2023-06-08 09:34
Mulig dette løser mitt problem også. Hvordan installere en beta?

**Comment by magne74** [comment] 2023-06-08 10:19
Fant ut av det og det løste mitt problem også.

**Comment by TorbjornMohn** [comment] 2023-06-08 10:28
> Fant ut av det og det løste mitt problem også.

Hvordan gjorde du det. Jeg finner ikke ut av det😢

**Comment by magne74** [comment] 2023-06-08 10:32
Gå inn i zaptec-integrasjonen i hacs. Velg last ned på nytt via de tre prikkene øverst i høyre hjørne. Tillat beta-versjoner. Så måtte jeg først velge 0.0.3 fra 0.0.5. Så fikk jeg lov til å velge den siste beta-versjonen...

**Comment by TorbjornMohn** [comment] 2023-06-08 11:14
> Gå inn i zaptec-integrasjonen i hacs. Velg last ned på nytt via de tre prikkene øverst i høyre hjørne. Tillat beta-versjoner. Så måtte jeg først velge 0.0.3 fra 0.0.5. Så fikk jeg lov til å velge den siste beta-versjonen...

TAKK!!!! :-)

**Comment by Olen** [comment] 2023-06-08 11:46
Bekrefter at siste beta fungerer her også.

**Comment by philsson** [comment] 2023-06-08 18:29
Just created a fork to fix this. Should not HACS propose an update if one is lagging behind?

**Comment by Olen** [comment] 2023-06-08 18:38
No need to create a fork.
Just install the latest beta from hacs.

**Comment by gertlind** [comment] 2023-06-09 06:40
Beta works perfectly, thanks for this.

**Comment by juicydut** [comment] 2023-06-09 08:51
when you say it works, does it mean you can see sensors/states of the charger? or it also means you are able to call the services (start, stop charging). When I tried to call start/stop charging service, it gives an error "required key not provided @ data['charger_id']" any suggestions? thx

**Comment by philsson** [comment] 2023-06-09 09:08
> when you say it works, does it mean you can see sensors/states of the charger? or it also means you are able to call the services (start, stop charging). When I tried to call start/stop charging service, it gives an error "required key not provided @ data['charger_id']" any suggestions? thx

I tried this just yesterday and it works. I have only had my charger for a couple of weeks and not played around with it too much yet but I've noticed that for me the charger needs to be "charging" before I can do anything from the zaptec service. I can then pause and resume, but if I have the charger in "smart mode" through Tibber then before it starts charging I cannot control it. So as far as I can tell the charger needs to be configured to always charge and then if you do not want to charge immediatly you'd have to pause it just after connecting the car. I would love to hear more from others on this but this "issue" may be the wrong forum for that. Anyways, here is some code I have in Lovelance

```yaml
type: horizontal-stack
cards:
  - show_name: true
    show_icon: true
    type: button
    icon: mdi:pause
    name: Stop Pause Charging
    tap_action:
      action: call-service
      service: zaptec.stop_pause_charging
      target: {}
      data:
        charger_id: bxxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
  - show_name: true
    show_icon: true
    type: button
    icon: mdi:play-pause
    name: Resume Charging
    tap_action:
      action: call-service
      service: zaptec.resume_charging
      data:
        charger_id: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
```

**Comment by juicydut** [comment] 2023-06-09 10:10
> 
Thanks for sharing the experience using the service, have just checked both stop_pause_charging and resume_charging service works fine after providing charger_id 👍  (when it is already charging.). 
Also have my charger for less then one month and thinking to build a "smart mode" locally in HA to utilize the solar panel (Tibber not available in DK).. I plan do more tests and report back if finding something meaningful..  😄

**Comment by jorgel272** [comment] 2023-06-10 21:47
The Zaptec integration was working correctly. After updating to HA Core version 2023.6.1 (From 2023.4.6), I am getting the same error: "Requirements for zaptec not found: ['azure-servicebus==7.0.1'].".

Rolled back to the backup of version HA Core version 2023.4.6 fixed the problem for now. 
Is anyone else having the same experience?

**Comment by Hellowlol** [comment] 2023-06-10 22:24
@jorgel272 did you even bother to read any of the posts in this issue? The fix is mentioned multiple times.

**Comment by jorgel272** [comment] 2023-06-11 06:22
@Hellowlol Yes, I did read the other posts! 

The fix is to update to the HACS beta, which will give you access to the latest version where you dropped the azure-servicebus==7.0.1 requirement in custom_components/zaptec/manifest.json.

I did not just switch to HACS beta because the topic starter mentioned that he had problems with Home Assistant 2023.6 _beta_ version. 

I installed the HACS beta version, which works like a charm in HA 2023.6 (non-beta). Awesome!

**Comment by cherealnice** [comment] 2023-06-12 18:08
Confirmed that latest beta of the component works

**Comment by Hellowlol** [comment] 2023-06-12 18:10
Azure-service bus is used if it’s available. If not it will poll every 60 seconds

**Comment by Hellowlol** [comment] 2023-06-12 18:15
Thanks for the confirmation guys. Ill close this issue and prompte the beta to a normal release in one of the upcoming days

**Comment by sveinse** [comment] 2023-09-17 13:10
It might be useful to know that I'm working on a significant improvement to zaptec, which also address the service bus issues. It is tracked in PR #56 which will be released once its stable. It is at beta test in my fork at https://github.com/sveinse/zaptec and is installable via HACS (yet I'd be careful on production environments). See the URL for instructions if you want to give it a go. I'm grateful for all feedback I can get.

**Comment by sveinse** [comment] 2023-11-11 18:21
I recommend installing the new 0.7.0 beta that fixes the issue with azure-servicebus. If there are no objections I'd like to close this issue.

**Comment by Olen** [comment] 2023-11-12 12:17
Not directly related to this, but 0.7.0 seems to work fine for me.
Some of the attributes is still missing as their own sensors but is seems like the new binary_sensor.xxxx_charger still contains all the attributes from the old sensor.xxx_serialnumber

**Comment by sveinse** [comment] 2023-11-12 13:48
@Olen please add a separate issue to which sensors you'd like to have added to zaptec. Is is rather trivial to add new ones if it comes in popular demand. -- And as you point out, the attr are still available for manual templates.

**Closed** 2023-11-19 19:51 UTC
